"use client";

import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";

export function QaTemplateButton() {
  const handleDownload = () => {
    // Generate a professional HTML layout that MS Word can open
    const htmlContent = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: 'Arial', sans-serif; color: #333; line-height: 1.5; }
          .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #000; padding-bottom: 10px; }
          .title { font-size: 24px; font-weight: bold; margin: 0; text-transform: uppercase; }
          .subtitle { font-size: 14px; color: #666; margin-top: 5px; }
          .meta-table { width: 100%; margin-bottom: 20px; font-size: 14px; }
          .meta-table td { padding: 5px; }
          .data-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          .data-table th, .data-table td { border: 1px solid #000; padding: 10px; text-align: center; font-size: 14px; }
          .data-table th { background-color: #f2f2f2; font-weight: bold; text-transform: uppercase; }
          .footer { margin-top: 50px; font-size: 12px; color: #888; text-align: center; }
          .signature { margin-top: 40px; width: 300px; float: right; text-align: center; }
          .signature-line { border-bottom: 1px solid #000; margin-top: 40px; }
        </style>
      </head>
      <body>
        <div class="header">
          <p class="title">EV BATTERY QA LAB REPORT</p>
          <p class="subtitle">ELEVAITE VOLT-GUARD QUALITY ASSURANCE TEMPLATE</p>
        </div>
        
        <table class="meta-table">
          <tr>
            <td><strong>Date of Inspection:</strong> ___________________</td>
            <td><strong>Inspector Name:</strong> ___________________</td>
          </tr>
          <tr>
            <td><strong>Facility Location:</strong> Main Assembly Line</td>
            <td><strong>Batch Approval:</strong> [   ] YES &nbsp;&nbsp; [   ] NO</td>
          </tr>
        </table>

        <p><em>* Mohon isi metrik Voltage dan Impedance dengan jelas. Dokumen ini akan dipindai oleh AI.</em></p>

        <table class="data-table">
          <tr>
            <th>No.</th>
            <th>Pallet ID</th>
            <th>Batch Vendor</th>
            <th>Avg Voltage (V)</th>
            <th>Impedance (m&Omega;)</th>
            <th>QA Remarks / Notes</th>
          </tr>
          <!-- Example Row -->
          <tr>
            <td>1</td>
            <td><strong>B-109</strong></td>
            <td>LG Chem</td>
            <td><strong>4.18</strong></td>
            <td><strong>1.2</strong></td>
            <td>Passed thermal check. Ready for release.</td>
          </tr>
          <!-- Empty Rows -->
          <tr><td>2</td><td>B-110</td><td>CATL</td><td></td><td></td><td></td></tr>
          <tr><td>3</td><td>B-111</td><td></td><td></td><td></td><td></td></tr>
          <tr><td>4</td><td></td><td></td><td></td><td></td><td></td></tr>
          <tr><td>5</td><td></td><td></td><td></td><td></td><td></td></tr>
        </table>

        <div class="signature">
          <p>Authorized by:</p>
          <div class="signature-line"></div>
          <p>Lead QA Engineer</p>
        </div>
        
        <div style="clear: both;"></div>
        <div class="footer">
          <p>Generated by Elevaite Volt-Guard System &copy; 2026. Document ID: QA-TMP-8821</p>
        </div>
      </body>
      </html>
    `;

    const blob = new Blob(["\ufeff", htmlContent], {
      type: "application/msword",
    });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", "EV_Battery_QA_Template.doc");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <Button
      onClick={handleDownload}
      variant="outline"
      className="rounded-full bg-blue-900 font-bold uppercase tracking-widest text-xs h-10 px-4 gap-2 border-white/20 hover:bg-white/5"
    >
      <Download className="h-4 w-4" />
      QA Template (Docs)
    </Button>
  );
}
