import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/utils/supabase/server";
import { cookies } from "next/headers";

export async function POST(req: NextRequest) {
  try {
    const cookieStore = await cookies();
    const supabase = createClient(cookieStore);
    
    const body = await req.json();
    const { pallet_id } = body;

    if (!pallet_id) {
      return NextResponse.json({ error: "pallet_id is required" }, { status: 400 });
    }

    // Fetch pallet data from Supabase
    const { data: pallet, error } = await supabase
      .from("pallets")
      .select("*")
      .eq("id", pallet_id)
      .single();

    if (error || !pallet) {
      return NextResponse.json({ error: "Pallet not found" }, { status: 404 });
    }

    // Use Azure OpenAI if API keys are available, otherwise use rule-based fallback
    const azureEndpoint = process.env.AZURE_COPILOT_ENDPOINT;
    const azureApiKey = process.env.AZURE_COPILOT_INTELLIGENCE_KEY;
    const deploymentName = process.env.AZURE_COPILOT_DEPLOYMENT || "gpt-4o-mini"; // Ganti jika nama deployment Anda berbeda

    if (azureEndpoint && azureApiKey) {
      const baseUrl = azureEndpoint.replace(/\/$/, "");
      const url = `${baseUrl}/openai/deployments/${deploymentName}/chat/completions?api-version=2024-02-15-preview`;

      const aiRes = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "api-key": azureApiKey,
        },
        body: JSON.stringify({
          messages: [
            {
              role: "system",
              content:
                "You are an expert EV Battery Safety Officer generating formal incident reports for a manufacturing facility. Be concise, professional, and always include safety recommendations. Use markdown formatting to make the report look clean.",
            },
            {
              role: "user",
              content: `Generate a formal incident report for the following EV battery pallet anomaly:\n\nPallet Code: ${pallet.pallet_code}\nLocation: ${pallet.location}\nVendor: ${pallet.vendor_name || pallet.vendor}\nCell Count: ${pallet.cell_count}\nCurrent Temperature: ${pallet.temperature}°C\nHumidity: ${pallet.humidity ?? "N/A"}%\nStatus: ${pallet.status}\nAlert Reason: ${pallet.alert_reason}\nTimestamp: ${pallet.last_updated}\n\nThe report must include: 1) Incident Summary, 2) Risk Assessment, 3) Immediate Actions Required, 4) Recommended Next Steps.`,
            },
          ],
          temperature: 0.3,
          max_tokens: 800,
        }),
      });

      if (!aiRes.ok) {
        const errorText = await aiRes.text();
        console.error("Azure OpenAI Error:", errorText);
        // Jika API error (misal salah key/endpoint), gunakan fallback agar app tidak crash
        const report = generateRuleBasedReport(pallet);
        return NextResponse.json({ report, pallet, error_fallback: true });
      }

      const aiData = await aiRes.json();
      const report = aiData.choices?.[0]?.message?.content;
      return NextResponse.json({ report, pallet });
    }

    // Fallback: Rule-based report (no API key needed — perfect for demo offline)
    const report = generateRuleBasedReport(pallet);
    return NextResponse.json({ report, pallet });
  } catch (err) {
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

function generateRuleBasedReport(pallet: Record<string, unknown>) {
  const temp = pallet.temperature as number;
  const riskLevel = temp >= 42 ? "CRITICAL" : temp >= 35 ? "HIGH" : "MEDIUM";
  const timestamp = new Date(pallet.last_updated as string).toLocaleString("id-ID", { timeZone: "Asia/Jakarta" });

  return `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ELEVAITE VOLT-GUARD — INCIDENT REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Ref: INC-${Date.now().toString().slice(-6)}
Timestamp: ${timestamp} WIB
Generated by: AI Safety Copilot v1.0

[1] INCIDENT SUMMARY
Pallet ${pallet.pallet_code} at ${pallet.location} (Vendor: ${pallet.vendor}) has been flagged with status ${pallet.status}. Recorded temperature: ${temp}°C — exceeds safe storage threshold. ${pallet.alert_reason}

[2] RISK ASSESSMENT
Severity: ${riskLevel}
${temp >= 42 ? "⚠️ THERMAL RUNAWAY risk detected. High probability of electrolyte ignition if not addressed immediately. This pallet contains ${pallet.cell_count} lithium cells." : "📊 Elevated temperature requires monitoring. No immediate thermal runaway risk, but continued exposure may degrade battery capacity and lifespan."}

[3] IMMEDIATE ACTIONS REQUIRED
• ✅ Auto-quarantine zone isolation: ACTIVATED
• 🚫 Block pallet from entering production line
• 🌡️ Deploy mobile cooling unit to zone immediately
• 📋 Notify QA Supervisor and Warehouse Manager

[4] RECOMMENDED NEXT STEPS
• Dispatch thermal camera inspection within 30 mins
• Contact vendor ${pallet.vendor} for batch recall inquiry
• Log incident to Traceability System (ITS)
• Schedule full batch inspection for all pallets from same vendor
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`;
}
