import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/utils/supabase/server";
import { cookies } from "next/headers";
import { AzureOpenAI } from "openai";

export async function POST(req: NextRequest) {
  try {
    const cookieStore = await cookies();
    const supabase = createClient(cookieStore);

    const body = await req.json();
    const { pallet_id } = body;

    if (!pallet_id) {
      return NextResponse.json(
        { error: "pallet_id is required" },
        { status: 400 },
      );
    }

    // Fetch pallet data from Supabase
    const { data: pallet, error } = await supabase
      .from("pallets")
      .select("*")
      .eq("id", pallet_id)
      .single();

    if (error || !pallet) {
      return NextResponse.json({ error: "Pallet not found" }, { status: 404 });
    }

    // Use Azure OpenAI if API keys are available, otherwise use rule-based fallback
    const azureEndpoint = process.env.AZURE_COPILOT_ENDPOINT;
    const azureApiKey = process.env.AZURE_COPILOT_INTELLIGENCE_KEY;
    const deploymentName = process.env.AZURE_COPILOT_DEPLOYMENT || "gpt-4.1-mini";

    if (azureEndpoint && azureApiKey) {
      try {
        const apiVersion = "2024-04-01-preview";
        const options = {
          endpoint: azureEndpoint,
          apiKey: azureApiKey,
          deployment: deploymentName,
          apiVersion,
        };

        const client = new AzureOpenAI(options);

        const aiResponse = await client.chat.completions.create({
          messages: [
            {
              role: "system",
              content: "You are a manufacturing quality analyst generating professional incident reports for an EV battery storage facility. Provide structured, data-driven analysis with clear action items.",
            },
            {
              role: "user",
              content: `Please generate a professional incident report for the following battery storage anomaly:\n\nPallet ID: ${pallet.pallet_code}\nStorage Location: ${pallet.location}\nSupplier: ${pallet.vendor_name || pallet.vendor}\nUnit Count: ${pallet.cell_count}\nRecorded Temperature: ${pallet.temperature}°C\nHumidity Level: ${pallet.humidity ?? "N/A"}%\nCurrent Status: ${pallet.status}\nAlert Description: ${pallet.alert_reason}\nRecorded At: ${pallet.last_updated}\n\nStructure the report with these sections:\n1. Incident Summary\n2. Risk Assessment\n3. Immediate Actions Required\n4. Recommended Next Steps`,
            },
          ],
          max_completion_tokens: 800,
          temperature: 1,
          top_p: 1,
          frequency_penalty: 0,
          presence_penalty: 0,
          model: deploymentName,
        });

        if ((aiResponse as any)?.error !== undefined) {
          throw (aiResponse as any).error;
        }

        const report = aiResponse.choices[0]?.message?.content;
        if (report) {
          console.log("✅ Azure AI report generated successfully");
          return NextResponse.json({ report, pallet });
        }
        throw new Error("Empty response from AI");
      } catch (aiErr: any) {
        console.error("⚠️ Azure AI failed, using fallback. Error:", aiErr?.message || aiErr?.status);
        // Gracefully fall through to rule-based report
      }
    }

    // Fallback: Rule-based report (no API key needed — perfect for demo offline)
    const report = generateRuleBasedReport(pallet);
    return NextResponse.json({ report, pallet, ai_fallback: true });
  } catch (err: any) {
    console.error("❌ Copilot Route Error:", err?.message || err);
    return NextResponse.json(
      { error: "Internal server error", detail: err?.message },
      { status: 500 },
    );
  }
}

function generateRuleBasedReport(pallet: Record<string, unknown>) {
  const temp = pallet.temperature as number;
  const riskLevel = temp >= 42 ? "CRITICAL" : temp >= 35 ? "HIGH" : "MEDIUM";
  const timestamp = new Date(pallet.last_updated as string).toLocaleString(
    "id-ID",
    { timeZone: "Asia/Jakarta" },
  );

  return `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ELEVAITE VOLT-GUARD — INCIDENT REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Ref: INC-${Date.now().toString().slice(-6)}
Timestamp: ${timestamp} WIB
Generated by: AI Safety Copilot v1.0

[1] INCIDENT SUMMARY
Pallet ${pallet.pallet_code} at ${pallet.location} (Vendor: ${pallet.vendor}) has been flagged with status ${pallet.status}. Recorded temperature: ${temp}°C — exceeds safe storage threshold. ${pallet.alert_reason}

[2] RISK ASSESSMENT
Severity: ${riskLevel}
${temp >= 42 ? "⚠️ THERMAL RUNAWAY risk detected. High probability of electrolyte ignition if not addressed immediately. This pallet contains ${pallet.cell_count} lithium cells." : "📊 Elevated temperature requires monitoring. No immediate thermal runaway risk, but continued exposure may degrade battery capacity and lifespan."}

[3] IMMEDIATE ACTIONS REQUIRED
• ✅ Auto-quarantine zone isolation: ACTIVATED
• 🚫 Block pallet from entering production line
• 🌡️ Deploy mobile cooling unit to zone immediately
• 📋 Notify QA Supervisor and Warehouse Manager

[4] RECOMMENDED NEXT STEPS
• Dispatch thermal camera inspection within 30 mins
• Contact vendor ${pallet.vendor} for batch recall inquiry
• Log incident to Traceability System (ITS)
• Schedule full batch inspection for all pallets from same vendor
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`;
}
